Repository CCDirectLink/CCModDB, pull requests merged in 2020-05, with the labels that each got.

#96 Updated ccloader and simplify
  input-locations.json
  mods.json
  npDatabase.json
  tools.json
Labels: update

#100 Fixed CharSwap link
  input-locations.json
  mods.json
  npDatabase.json
Labels: update

#99 Added some error logging
  build/src/source.ts
Labels: bug

#101 update crosscode-ru v1.0.5, enhanced-ui v0.1.3, jetpack v0.2.0
  input-locations.json
  mods.json
  npDatabase.json
Labels: update

#102 crosscode-ru hotfixes
  mods.json
  npDatabase.json
Labels: update

#103 crosscode-ru hotfixes 2
  input-locations.json
  mods.json
  npDatabase.json
Labels: new, update
